language: python
arch:
    - amd64
    - arm64
    - ppc64le

python:
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9-dev"

before_install:
    - pip install git+https://github.com/pytoolz/toolz.git
    - pip install cython pytest

install:
    - python setup.py build_ext --inplace --with-cython
    - pip install -e .

# commands to run tests
script:
    - nosetests --with-doctest cytoolz
    # For convenience, make sure simple test commands work
    - py.test
    - nosetests
    # Make sure we can cimport cytoolz
    - echo 'cimport cytoolz ; from cytoolz.functoolz cimport memoize' > try_cimport_cytoolz.pyx
    - cythonize -i try_cimport_cytoolz.pyx
    - python -c 'import try_cimport_cytoolz'

notifications:
  email: false
