language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7-dev"

# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
    include:
    - python: 3.7
      dist: xenial
      sudo: true

before_install:
    - pip install toolz==0.10.0
    - pip install pytest

install:
    - python setup.py build_ext --inplace --without-cython

# commands to run tests
script:
    - nosetests --with-doctest cytoolz
    # For convenience, make sure simple test commands work
    - py.test
    - nosetests

notifications:
  email: false
